---@meta
---@class debugSliderDef
---@field public label string
---@field public min number
---@field public max number
---@field public step number
---@field public default number
---@field public onChange fun(value: number)

---@class debugSliderSection.create.param
---@field public parent tes3uiElement
---@field public title string
---@field public sliders debugSliderDef[]
---@field public onCopy (fun(): string)|nil
