---@meta
---@class debugAnimationEntry : debugDropdownEntry
---@field public animation? animationDefinition
---@field public dialogueId? string
---@field public configuration? overrideAnimationConfiguration
---@field public baseConfiguration? baseAnimationConfiguration
