---@meta
--- A single selectable entry in the debug animation-preview dropdown. A "base"
--- entry forces its clip directly; an "override" entry fires a synthetic
--- dialogueInfo for its dialogueId, driving the animation and prop as in-game.
---@class previewEntry
---@field public label string
---@field public kind "base"|"override"
---@field public animation? animationDefinition
---@field public dialogueId? string
---@field public configuration? overrideAnimationConfiguration

--- A captioned dropdown of previewEntries in the debug HUD, with its live header
--- element, the block its expanded list renders into, and its selection callback.
---@class previewDropdown
---@field public entries previewEntry[]
---@field public header tes3uiElement
---@field public listParent tes3uiElement
---@field public open boolean
---@field public onSelect fun(entry: previewEntry)
