---@meta
---@class previewEntry : debugDropdownEntry
---@field public animation? animationDefinition
---@field public dialogueId? string
---@field public configuration? overrideAnimationConfiguration
