---@meta
---@alias reason string|nil
---@alias callback fun()
---@alias eventId string
---@alias eventHandlers { [eventId]: callback|callbackWithOptions }
---@alias eventHandlerGroups table<string, eventHandlers>

---@meta
---@class callbackWithOptions
---@field [1] callback
---@field [2] event.register.options?
