---@meta
---@class Mcm
---@field AnimateCamera boolean
---@field CameraDistance number
---@field CameraVerticalOffset number
---@field CameraHorizontalOffset number
---@field BlacklistedNpcs string[]
---@field EnableNpcAnimations boolean
---@field EnableNpcLipsyncing boolean
---@field EnableNpcTalkAnimations boolean
---@field EnableLookAtCamera boolean