---@meta
---@class voiceConfiguration : filterableConfiguration
---@field public sounds string[] Paths below Data Files\Sound. Interchangeable variants; one is picked per line.
---@field public conditions? conditions
---@field public weight? number
---@field public delay? number Seconds to wait before playing. Never shorter than the voiceLineMinimumDelay setting.
---@field public pitch? number Pitch shift multiplier, where 1.0 is unaltered. Unset, the sound plays as authored.
---@field public source? string The JSON filename this was loaded from (set at load time, not authored).
---@field public keywordPatterns? string[] Compiled from conditions.keywords at load time, not authored.

--- A voice configuration file is an array of these entries, so a single JSON
--- file can define a whole per-race set.
---@alias voiceConfigurationFile voiceConfiguration[]
