---@meta
---@class bodySkeletonTicker.state
---@field actor tes3reference|nil
---@field start number
---@field stop number
---@field phase number
---@field pinner bodyBonePinner
---@field poseBlender actorPoseBlender|nil
---@field transitionDuration number
