---@meta
---@class bodyAnimator : actorAnimator
---@field handles fun(reference: tes3reference): boolean
---@field create fun(): bodyAnimator
---@field begin fun(self: bodyAnimator, reference: tes3reference)
---@field onDialogueInfo? fun(self: bodyAnimator, info: tes3dialogueInfo)
---@field overridesLookAt? fun(self: bodyAnimator): boolean
---@field play? fun(self: bodyAnimator, params: clipBodyAnimator.play.param)
---@field stop fun(self: bodyAnimator)
---@field suppressesTurn? boolean
---@field preferredAnimationId? string|nil Base configuration id the clip strategy resolves ahead of the context-driven pick. Set between create and begin.

--- Which strategies a participant has enabled, keyed by strategy kind.
---@class bodyAnimatorToggles
---@field creature boolean
---@field native boolean
---@field clip boolean

---@class bodyAnimatorStrategy
---@field kind string
---@field animator bodyAnimator
