---@meta
---@class bodySkeletonTicker.state
---@field actor tes3reference|nil
---@field start number
---@field stop number
---@field phase number
---@field pins { node: niNode, translation: tes3vector3 }[]
