---@meta

---@class settings
---@field cameraEnabled boolean
---@field npcAnimEnabled boolean
---@field npcTurnEnabled boolean
---@field npcHeadAnimEnabled boolean
---@field distance number
---@field horizontalOffset number
---@field verticalOffset number
---@field pitchOffset number
---@field yawOffset number
---@field rollOffset number
---@field animationDuration number
---@field turnDuration number
